sdk: unset PKG_CONFIG when making modules_prepare
* Fixes compilation error:
   /usr/bin/ld: cannot find /lib64/libc.so.6: No such file or directory
   /usr/bin/ld: cannot find /usr/lib64/libc_nonshared.a: No such file or directory
   collect2: error: ld returned 1 exit status

  This error occurs because we use PKG_CONFIG when making modules_prepare. When
  compiling extract-cert, pkg-config will add "-L${sysroot}/usr/lib64 -lcrypto".
  "${sysroot}/usr/lib64" includes a link script for libc.so, it points to "/lib64/libc.so.6",
  but on ubuntu the libc.so is installed in "/lib/${arch}/libc.so". To fix this problem,
  we just unset PKGCONFIG when making modules_prepare. This is may not quite right,
  but it is a quick fix.

Signed-off-by: hanzongcheng <hanzongcheng@huawei.com>