dsoftbus: backport some patches
* We need to include mutex.h to fix:
   error: 'unique_lock' is not a member of 'std'
* Fix CVE-2023-30364 for libcoap.

Signed-off-by: hanzongcheng <hanzongcheng@huawei.com>