mcs: fix dev-elf QA error
Add shared library libmica.so to main package FILES:${PN} and skip
dev-elf QA check. libmica.so has no version number (like libmica.so.1),
which causes Yocto QA check to fail. This is acceptable for mica library.

Fixes the QA error during build:
ERROR: -dev package mcs-linux-dev contains non-symlink .so '/usr/lib64/libmica.so' [dev-elf]

Signed-off-by: Shi Xin <shixin21@h-partners.com>